#8 add write method overload with input stream
globocom/ghdfs pull request #13
Opened 2019-10-19 20:32 UTC by fg-devs

2019-10-19 20:33 UTC, fg-devs commented
Refs #8

2019-10-21 20:44 UTC, regismachado requested changes

2019-10-21 20:44 UTC, regismachado commented on src/main/scala/com/globo/bigdata/ghdfs/HdfsManager.scala
> +  def write(hadoopPath: Path, is: InputStream): Boolean = {
About the InputStream argument, can you change the variable name from "is" to another thing like "input"?

2019-10-21 20:44 UTC, regismachado commented on src/main/scala/com/globo/bigdata/ghdfs/HdfsManager.scala
> +    val fsOutputStream = create(hadoopPath)
Change the call of the create(..)  to the write(..).

Today create and write are similar, but maybe in the future, we will add new behaviours to the write

2019-11-11 14:48 UTC, dmvieira commented
Please solve conflicts @fg-devs

2019-11-11 17:01 UTC, fg-devs commented
@dmvieira resolved

2019-11-11 18:37 UTC, dmvieira commented
Thx!!!

2019-11-11 18:37 UTC, merged